# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_readme_error',
                'doc_host': 'https://shym.github.io',
                'git_url': 'https://github.com/shym/nbdev_readme_error',
                'lib_path': 'nbdev_readme_error'},
  'syms': {'nbdev_readme_error.core': {'nbdev_readme_error.core.foo': ('core.html#foo', 'nbdev_readme_error/core.py')}}}